

public class WrapTest {
    @org.junit.Test(timeout = 2000)
    public void test_0() throws java.lang.Exception {
        java.util.ArrayList result = correct_java_programs.WRAP.wrap((java.lang.String)"The leaves did not stir on the trees, grasshoppers chirruped, and the monotonous hollow sound of the sea rising up from below, spoke of the peace, of the eternal sleep awaiting us. So it must have sounded when there was no Yalta, no Oreanda here; so it sounds now, and it will sound as indifferently and monotonously when we are all no more. And in this constancy, in this complete indifference to the life and death of each of us, there lies hid, perhaps, a pledge of our eternal salvation, of the unceasing movement of life upon earth, of unceasing progress towards perfection. Sitting beside a young woman who in the dawn seemed so lovely, soothed and spellbound in these magical surroundings - the sea, mountains, clouds, the open sky - Gurov thought how in reality everything is beautiful in this world when one reflects: everything except what we think or do ourselves when we forget our human dignity and the higher aims of our existence.",(int)50);
        org.junit.Assert.assertEquals(new java.util.ArrayList(java.util.Arrays.asList("The leaves did not stir on the trees, grasshoppers"," chirruped, and the monotonous hollow sound of the"," sea rising up from below, spoke of the peace, of"," the eternal sleep awaiting us. So it must have"," sounded when there was no Yalta, no Oreanda here;"," so it sounds now, and it will sound as"," indifferently and monotonously when we are all no"," more. And in this constancy, in this complete"," indifference to the life and death of each of us,"," there lies hid, perhaps, a pledge of our eternal"," salvation, of the unceasing movement of life upon"," earth, of unceasing progress towards perfection."," Sitting beside a young woman who in the dawn"," seemed so lovely, soothed and spellbound in these"," magical surroundings - the sea, mountains,"," clouds, the open sky - Gurov thought how in"," reality everything is beautiful in this world"," when one reflects: everything except what we"," think or do ourselves when we forget our human"," dignity and the higher aims of our existence.")), result);
    }

    @org.junit.Test(timeout = 2000)
    public void test_1() throws java.lang.Exception {
        java.util.ArrayList result = correct_java_programs.WRAP.wrap((java.lang.String)"The leaves did not stir on the trees, grasshoppers chirruped, and the monotonous hollow sound of the sea rising up from below, spoke of the peace, of the eternal sleep awaiting us. So it must have sounded when there was no Yalta, no Oreanda here; so it sounds now, and it will sound as indifferently and monotonously when we are all no more. And in this constancy, in this complete indifference to the life and death of each of us, there lies hid, perhaps, a pledge of our eternal salvation, of the unceasing movement of life upon earth, of unceasing progress towards perfection. Sitting beside a young woman who in the dawn seemed so lovely, soothed and spellbound in these magical surroundings - the sea, mountains, clouds, the open sky - Gurov thought how in reality everything is beautiful in this world when one reflects: everything except what we think or do ourselves when we forget our human dignity and the higher aims of our existence.",(int)20);
        org.junit.Assert.assertEquals(new java.util.ArrayList(java.util.Arrays.asList("The leaves did not"," stir on the trees,"," grasshoppers"," chirruped, and the"," monotonous hollow"," sound of the sea"," rising up from"," below, spoke of the"," peace, of the"," eternal sleep"," awaiting us. So it"," must have sounded"," when there was no"," Yalta, no Oreanda"," here; so it sounds"," now, and it will"," sound as"," indifferently and"," monotonously when"," we are all no more."," And in this"," constancy, in this"," complete"," indifference to the"," life and death of"," each of us, there"," lies hid, perhaps,"," a pledge of our"," eternal salvation,"," of the unceasing"," movement of life"," upon earth, of"," unceasing progress"," towards perfection."," Sitting beside a"," young woman who in"," the dawn seemed so"," lovely, soothed and"," spellbound in these"," magical"," surroundings - the"," sea, mountains,"," clouds, the open"," sky - Gurov thought"," how in reality"," everything is"," beautiful in this"," world when one"," reflects:"," everything except"," what we think or do"," ourselves when we"," forget our human"," dignity and the"," higher aims of our"," existence.")), result);
    }

    @org.junit.Test(timeout = 2000)
    public void test_2() throws java.lang.Exception {
        java.util.ArrayList result = correct_java_programs.WRAP.wrap((java.lang.String)"The leaves did not stir on the trees, grasshoppers chirruped, and the monotonous hollow sound of the sea rising up from below, spoke of the peace, of the eternal sleep awaiting us. So it must have sounded when there was no Yalta, no Oreanda here; so it sounds now, and it will sound as indifferently and monotonously when we are all no more. And in this constancy, in this complete indifference to the life and death of each of us, there lies hid, perhaps, a pledge of our eternal salvation, of the unceasing movement of life upon earth, of unceasing progress towards perfection. Sitting beside a young woman who in the dawn seemed so lovely, soothed and spellbound in these magical surroundings - the sea, mountains, clouds, the open sky - Gurov thought how in reality everything is beautiful in this world when one reflects: everything except what we think or do ourselves when we forget our human dignity and the higher aims of our existence.",(int)80);
        org.junit.Assert.assertEquals(new java.util.ArrayList(java.util.Arrays.asList("The leaves did not stir on the trees, grasshoppers chirruped, and the monotonous"," hollow sound of the sea rising up from below, spoke of the peace, of the"," eternal sleep awaiting us. So it must have sounded when there was no Yalta, no"," Oreanda here; so it sounds now, and it will sound as indifferently and"," monotonously when we are all no more. And in this constancy, in this complete"," indifference to the life and death of each of us, there lies hid, perhaps, a"," pledge of our eternal salvation, of the unceasing movement of life upon earth,"," of unceasing progress towards perfection. Sitting beside a young woman who in"," the dawn seemed so lovely, soothed and spellbound in these magical surroundings"," - the sea, mountains, clouds, the open sky - Gurov thought how in reality"," everything is beautiful in this world when one reflects: everything except what"," we think or do ourselves when we forget our human dignity and the higher aims"," of our existence.")), result);
    }

    @org.junit.Test(timeout = 2000)
    public void test_3() throws java.lang.Exception {
        java.util.ArrayList result = correct_java_programs.WRAP.wrap((java.lang.String)"The leaves did not stir on the trees, grasshoppers chirruped, and the monotonous hollow sound of the sea rising up from below, spoke of the peace, of the eternal sleep awaiting us. So it must have sounded when there was no Yalta, no Oreanda here; so it sounds now, and it will sound as indifferently and monotonously when we are all no more. And in this constancy, in this complete indifference to the life and death of each of us, there lies hid, perhaps, a pledge of our eternal salvation, of the unceasing movement of life upon earth, of unceasing progress towards perfection. Sitting beside a young woman who in the dawn seemed so lovely, soothed and spellbound in these magical surroundings - the sea, mountains, clouds, the open sky - Gurov thought how in reality everything is beautiful in this world when one reflects: everything except what we think or do ourselves when we forget our human dignity and the higher aims of our existence.",(int)77);
        org.junit.Assert.assertEquals(new java.util.ArrayList(java.util.Arrays.asList("The leaves did not stir on the trees, grasshoppers chirruped, and the"," monotonous hollow sound of the sea rising up from below, spoke of the peace,"," of the eternal sleep awaiting us. So it must have sounded when there was no"," Yalta, no Oreanda here; so it sounds now, and it will sound as indifferently"," and monotonously when we are all no more. And in this constancy, in this"," complete indifference to the life and death of each of us, there lies hid,"," perhaps, a pledge of our eternal salvation, of the unceasing movement of"," life upon earth, of unceasing progress towards perfection. Sitting beside a"," young woman who in the dawn seemed so lovely, soothed and spellbound in"," these magical surroundings - the sea, mountains, clouds, the open sky -"," Gurov thought how in reality everything is beautiful in this world when one"," reflects: everything except what we think or do ourselves when we forget our"," human dignity and the higher aims of our existence.")), result);
    }

    @org.junit.Test(timeout = 2000)
    public void test_4() throws java.lang.Exception {
        java.util.ArrayList result = correct_java_programs.WRAP.wrap((java.lang.String)"The leaves did not stir on the trees, grasshoppers chirruped, and the monotonous hollow sound of the sea rising up from below, spoke of the peace, of the eternal sleep awaiting us. So it must have sounded when there was no Yalta, no Oreanda here; so it sounds now, and it will sound as indifferently and monotonously when we are all no more. And in this constancy, in this complete indifference to the life and death of each of us, there lies hid, perhaps, a pledge of our eternal salvation, of the unceasing movement of life upon earth, of unceasing progress towards perfection. Sitting beside a young woman who in the dawn seemed so lovely, soothed and spellbound in these magical surroundings - the sea, mountains, clouds, the open sky - Gurov thought how in reality everything is beautiful in this world when one reflects: everything except what we think or do ourselves when we forget our human dignity and the higher aims of our existence.",(int)140);
        org.junit.Assert.assertEquals(new java.util.ArrayList(java.util.Arrays.asList("The leaves did not stir on the trees, grasshoppers chirruped, and the monotonous hollow sound of the sea rising up from below, spoke of the"," peace, of the eternal sleep awaiting us. So it must have sounded when there was no Yalta, no Oreanda here; so it sounds now, and it will"," sound as indifferently and monotonously when we are all no more. And in this constancy, in this complete indifference to the life and death"," of each of us, there lies hid, perhaps, a pledge of our eternal salvation, of the unceasing movement of life upon earth, of unceasing"," progress towards perfection. Sitting beside a young woman who in the dawn seemed so lovely, soothed and spellbound in these magical"," surroundings - the sea, mountains, clouds, the open sky - Gurov thought how in reality everything is beautiful in this world when one"," reflects: everything except what we think or do ourselves when we forget our human dignity and the higher aims of our existence.")), result);
    }
}

